name: Python linting and testing
run-name: Testing Workflow
on: [push]

jobs:
    build:
          runs-on: ubuntu-latest
          steps:
                name: Installing latest python
                uses: actions/setup-python@4.5.0
                with:
                    python-version: '3.x'
                name: Installing pip and dependecies
                run: |
                     python -m pip install --upgrade pip
                     pip install -r requirements.txt
                name: Linting with flake 8
                run: flake8 . 

